name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install dependencies
      run: dotnet restore Humphrey.Tests
    - name: Build
      run: dotnet build Humphrey.Tests --configuration Release --no-restore
    - name: Test
      run: dotnet test Humphrey.Tests --no-restore --verbosity normal
